### ISSUE TITLE
when multiple download function executed warnining appears

### ISSUE THREAD

**Issue by iamnotagentleman** [SpeedyDM/speedy-core#15]
how to get the warning(ex. situation) ?
: run the followings: `npm test`

warning : (node:7060) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 pause listeners added to [InfoEmitter]. Use emitter.setMaxListeners() to increase limit

**Comment by AtakanErmis** [comment]
This is actually happens when you want to use 11 or more instance. Node.js thinks there might be a memory leak but download continues and finishes successfully. I'm investigating this and might create a fix. Thanks.

**Comment by AtakanErmis** [comment]
This warning shows because of infoEmitter listens pause event for all workers and node thinks there might be a memory leak but actually not. We can ignore this or add a instance limit to download function. What do you think?

**Comment by AtakanErmis** [comment]
Appearently we can set max listener count explicitly with `emitter.setMaxListeners(Number)`.

**Comment by iamnotagentleman** [comment]
if u ask me we should add a instance limit. because some developers encounter this error and they can try to deal with it, and the second reason is  possibility of duplicate issues.

**Comment by AtakanErmis** [comment]
I added instance limit of 10 since node doesn't recommend more than 10 instance. I'm closing issue.
