### ISSUE TITLE
part files overwritten.

### ISSUE THREAD

**Issue by iamnotagentleman** [SpeedyDM/speedy-core#24]
TEST CASE : 
execute a download let's say a.file
abort the download before the download finished
execute again a download a.file

Expected Result : 
identical file 
The Result: 
broken file

the part files broken because the code append the new data should rewrite or should continue from where it stopped

**Comment by AtakanErmis** [comment]
pls git pull origin master for god's sake

**Comment by iamnotagentleman** [comment]
if god exist it's fucking me the branch already updated the latest version please run tests again

**Comment by iamnotagentleman** [comment]
solved.
