### ISSUE TITLE
JSON.stringify(state).fileName returns undefined

### ISSUE THREAD

**Issue by iamnotagentleman** [SpeedyDM/speedy-core#25]
when i tried get fileName from json of state the filename returns undefined check : #issue-#21 branch

src/download.js -> writeState

**Comment by AtakanErmis** [comment]
you cannot access stringified json because it's string not object. Don't use stringify and give straight state to function. And appearently there is a typo in line 17, fileNamee instead of fileName. Stringify json in writeFile function.
